---
version: '3.5'
services:

  slate:
    image: api-docs:latest
    build: .
    ports:
      - target: 4567
        published: 4567
    tty: true
    volumes:
    - type: bind
      source: './source'
      target: '/srv/slate/source'
      read_only: true

