name: build and deploy

on:
  push:
    branches:
    - master

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: bundle install
      run: |
        gem install bundler -v 2.4.2
        bundle install --jobs 4 --retry 3

    - run: bundle exec middleman build --clean

    - name: deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages
